config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get "/auth/twitch", as: "login"

  get "/auth/twitch/callback", to: "sessions#create"

  get "/logout", to: "sessions#destroy", as: "logout"

  resources :stream, param: :stream_name, only: [:show]
  resources :user, param: :username, only: [:show]
  resources :channels, param: :channel_name, only: [:show]
  
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid          = auth_info.uid
      new_user.display_name = auth_info.info.name
      new_user.email        = auth_info.info.email
      new_user.bio          = auth_info.info.description
      new_user.image_url    = auth_info.info.image
      new_user.oauth_token  = auth_info.credentials.token
      new_user.partnered    = auth_info.extra.raw_info.partnered
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController

  def show
    @channel = TwitchService.current_channel(params[:channel_name])
    @videos = @channel.videos(limit: 10)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/stream_controller.rb
class StreamController < ApplicationController

  def show
    @stream_name = params[:stream_name]
    @stream = TwitchService.current_stream(@stream_name)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
    @user = current_user
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  helper_method :parse_name

  def index
    @streams = TwitchService.streams(50)
  end

  private

    def parse_name(name)
      name = name.sub("live_user_", "")
      name.capitalize
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stream_helper.rb
module StreamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/channels/show.html.erb
<div class="container">
  <h1 class="profile-header exo"><%= image_tag(@channel.logo_url)%><%= @channel.display_name %></h1>
  <% if @channel.streaming? %>
    <h4><%= link_to "Live now!", stream_path(stream_name: @channel.display_name)%></h4>
  <% end %>

  <h3 class="large-top-margin">Videos:</h3>
  <div class="row">
    <% @videos.each do |video| %>
      <div class="col s4 m4">
        <div class="card">
          <div class="card-image">
            <%= link_to image_tag(video.preview_url), video.url %>
            <span class="card-title"><i class="small material-icons med-left-margin">input</i></span>
          </div>
          <span class="card-title"><%= video.title %></span>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blink</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<%= render partial: "partials/navbar" %>
<%= yield %>

</body>
</html>

app/views/partials/_navbar.html.erb
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper purple darken-3">
      <h4 class="brand-logo small-left-margin exo">
        <%= link_to "Blink", root_path %>
      </h4>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if current_user %>
          <li>
            <%= link_to current_user.display_name, user_path(username: current_user.display_name) %>
          </li>
          <li>
            <%= link_to "Log out", logout_path %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", login_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/stream/show.html.erb
<div class="med-left-margin small-top-margin">
<h4><%= link_to @stream_name, channel_path(@stream_name) %></h4>
  <iframe 
      src="http://player.twitch.tv/?channel=<%= @stream_name %>" 
      height="720" 
      width="1280" 
      frameborder="0" 
      scrolling="no" 
      allowfullscreen>
  </iframe>
  <iframe frameborder="0" 
        scrolling="no" 
        id="chat_embed" 
        src="http://www.twitch.tv/<%= @stream_name %>/chat" 
        height="720" 
        width="325">
  </iframe>
</div>

app/views/user/show.html.erb
<div class="container">
  <h1 class="profile-header exo"><%= image_tag(@user.image_url)%><%= @user.display_name %></h1>
  <h3 class="exo"><%= @user.email%></h3>
  <p class="exo"><%= @user.bio%></p>
</div>

app/views/welcome/index.html.erb
<div class="container small-top-margin">
  <div class="row">
    <% @streams.each do |stream| %>
      <div class="col s4 m4">
        <div class="card">
          <div class="card-image exo">
            <%= link_to image_tag(stream.preview_url), stream_path(stream_name: parse_name(stream.name))%>
            <span class="card-title"><i class="small material-icons med-left-margin">input</i></span>
          </div>
          <div class="card-content">
            <span class="card-title"><%= link_to parse_name(stream.name), channel_path(channel_name: parse_name(stream.name)) %></span>
            <h6><i class="small material-icons med-left-margin">perm_identity</i><%= stream.viewer_count%></h6>
            <p><i class="small material-icons med-left-margin">play_arrow</i><%= stream.game_name %></p>
          </div>
        </div>
      </div>
    <% end%>
  </div>
</div>